version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::374958087690:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-1BISUHEG9RL01"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::374958087690:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1CRJXRXFDTTQO"
cloudformation_execution_role = "arn:aws:iam::374958087690:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-X4ZAANMQLWC4"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-10q2hlruj6s19"
image_repository = ""
region = "us-west-1"

[stage]
[stage.pipeline_bootstrap]
[stage.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::374958087690:role/aws-sam-cli-managed-stage-pi-PipelineExecutionRole-1V1NXYRXJ629O"
cloudformation_execution_role = "arn:aws:iam::374958087690:role/aws-sam-cli-managed-stage-CloudFormationExecutionR-YY2U6QRO5R2J"
artifacts_bucket = "aws-sam-cli-managed-stage-pipelin-artifactsbucket-1qibrw1knz9vi"
image_repository = ""
region = "us-west-1"
